name: reusable-call-echo

on:
  workflow_dispatch:

jobs:
  call-echo1:
    uses: collinmcneese-test/.github/.github/workflows/echo1.yml@v1.0.0
  call-echo2:
    uses: collinmcneese-test/.github/.github/workflows/echo2.yml@v1
    
