name: issue-labels

on:
  issues:
      types: [labeled]

jobs:
  labeled:
    runs-on: ubuntu-latest
    if: contains(github.event.label.name, 'duplicate')
    #if: github.event.label.name == 'bug'
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          console.log(context)
  wf:
    uses: ./.github/workflows/issue-workflow-called.yml
