name: workflow-metrics
on:
  workflow_dispatch:

jobs:
  evaluate-actions-consumption:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Date Set
        id: date-set
        run: |
          echo "start_date=$(date --date '7 days ago' +'%Y-%m-%d')" >> "${GITHUB_OUTPUT}"
          echo "end_date=$(date +'%Y-%m-%d')" >> "${GITHUB_OUTPUT}"
      - name: Call workflow-runs action
        uses: kittychiu/workflow-metrics@v0.4.7
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER_NAME: ${{ github.event.repository.owner.login }}
          REPO_NAME: ${{ github.event.repository.name }}
          START_DATE: ${{ steps.date-set.outputs.start_date }}
          END_DATE: ${{ steps.date-set.outputs.end_date }}
      - name: Convert workflow-stats.CSV to stats-table.md markdown table
        run: |
          echo -e "## Table View\n" > stats-table.md
          header=$(head -n 1 workflow-stats.csv | sed 's/,/|/g' | sed 's/_/ /g')
          echo -e "|${header}|" >> stats-table.md
          metadata=$(head -n 1 workflow-stats.csv | sed 's/,/|/g' | sed 's/[^|]/-/g')
          echo -e "|${metadata}|" >> stats-table.md
          tail -n +2 workflow-stats.csv | sed 's/,/|/g; s/^/|/; s/$/|/' >> stats-table.md

      - name: Convert workflow-stats.CSV to stream-diagram.md mermaid diagram
        run: |
          echo -e "## Value Stream View\n" > stream-diagram.md
          echo -e '```mermaid' >> stream-diagram.md
          echo -e 'timeline' >> stream-diagram.md
          head -n 1 workflow-stats.csv | sed 's/,/ : /g' | sed 's/_/ /g' | awk -F'|' '{for(i=1;i<=NF;i++) printf("%s%s", "    ", $i, i==NF?"\n":", ")}' | sed 's/^/  /' >> stream-diagram.md
          tail -n +2 workflow-stats.csv | sed 's/,/ : /g' | awk -F'|' '{for(i=1;i<=NF;i++) printf("%s%s", "\n    ", $i, i==NF?"\n":", ")}' | sed 's/^/  /' >> stream-diagram.md
          echo -e '\n```' >> stream-diagram.md

      - name: Combine into output content
        run: |
          echo "Combine output files"
          cat stream-diagram.md stats-table.md >> $GITHUB_STEP_SUMMARY
          
